comment: false

coverage:
  round: up
  precision: 0
  status:
    project:
      default:
        target: 90
        threshold: null
        informational: true
    patch:
      default:
        target: 0
        threshold: null
        informational: true
